apiVersion: v1
kind: Service
metadata:
  name: vote-app
spec:
  type: NodePort
  selector:
    app: vote-app   # Must match deployment label
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 80    # Container port
      nodePort: 30007   # External port (range: 30000â€“32767)
